bad_foods = {
    "Dog": [
        "chocolate",
        "chocolates",
        "grapes",
        "onions",
        "grape",
        "onion",
        "fudge",
        "macadamia nuts",
        "corn",
        "corn on the cob",
        "garlic",
        "chives",
        "avocado",
        "sweetener",
        "xylitol",
        "alcohol",
        "nut",
        "beer",
        "liquor",
        "cooked bones",
        "cooked bone",
        "raisins",
        "rat poison",
        "rat killer",
        "rat",
        "poison",
        "killer",
        "raw meat",
        "raw fish",
        "raw egg",
        "raw eggs",
        "salt",
        "sugar",
        "fat",
        "dairy",
        "milk",
        "cheese",
        "ice cream",
        "butter",
        "yogurt",
        "coconut",
        "coconut water",
        "nuts",
        "fruit pits",
        "fruit seeds",
        "apple seeds",
        "peach pits",
        "peach seeds",
        "cherry pits",
        "cherry seeds",
        "apricot pits",
        "apricot seeds",
        "plum pits",
        "plum seeds",
        "tomato leaves",
        "tomato plants",
        "tomato",
        "leaves",
        "plants",
        "mushrooms",
        "mushroom",
        "house plant",
        "house plants",
        "bread",
        "pasta",
        "cookies",
        "crackers",
        "chips",
        "raw potatos",
        "raw potato",
        "potato",
        "potatos",
        "potatoes",
        "raw potato",
        "raw potatoes",
        "potato",
        "potatos",
    ],
    "Cat": [
        "lilies",
        "chives",
        "alcohol",
        "dough",
        "yeast",
        "chocolate",
        "coffee",
        "citrus",
        "citrus fruits",
        "coconut",
        "coconut water",
        "dairy",
        "grapes",
        "grape",
        "raisin",
        "raisins",
        "nuts",
        "raw egg",
        "raw meat",
        "raw fish",
        "salt",
        "leeks",
        "scallions",
        "shallots",
        "xylitol",
        "fat",
        "fruit pits",
        "fruit seeds",
        "apple seeds",
        "peach pits",
        "peach seeds",
        "cherry pits",
        "cherry seeds",
        "apricot pits",
        "apricot seeds",
        "plum pits",
        "plum seeds",
        "tomato leaves",
        "tomato plants",
        "tomato",
        "leaves",
        "plant",
        "plants",
        "mushrooms",
        "mushroom",
        "house plant",
        "house plants",
        "bread",
        "pasta",
        "cookies",
        "crackers",
        "chips",
        "raw potatos",
        "raw potato",
        "potato",
        "potatos",
        "potatoes",
        "raw potato",
        "raw potatoes",
        "potato",
        "potatos",
    ],
}

good_foods = {
    "Dog": [
        "carrots",
        "carrot",
        "apple",
        "apples",
        "white rice",
        "milk",
        "cheese",
        "yogurt",
        "cooked fish",
        "cooked chicken",
        "cooked turkey",
        "cooked beef",
        "cooked pork",
        "cooked lamb",
        "cooked venison",
        "cooked bison",
        "cooked rabbit",
        "cooked duck",
        "cooked goose",
        "plain popcorn",
        "blueberries",
        "banana",
        "bananas",
        "cucumber",
        "cucumbers",
        "green beans",
        "green bean",
    ],
    "Cat": [
        "carrots",
        "carrot",
        "apple",
        "apples",
        "white rice",
        "milk",
        "cheese",
        "yogurt",
        "cooked fish",
        "cooked chicken",
        "cooked turkey",
        "cooked beef",
        "cooked pork",
        "cooked lamb",
        "cooked venison",
        "cooked bison",
        "cooked rabbit",
        "cooked duck",
        "cooked goose",
        "plain popcorn",
        "blueberries",
        "banana",
        "bananas",
        "cucumber",
        "cucumbers",
        "green beans",
        "green bean",
    ],
}
